$schema: https://json-schema.org/draft/2020-12/schema
maturityAttributes:
  productionStatus: PROD
securityAttributes:
  defaultGranularity: record
  securityLevels:
    - PUBLIC
entryTypes:

  dataset:
    id: dataset
    name: Dataset
    ontologyTermForThisType:
      id: NCIT:C47824
      label: Data set
    partOfSpecification: Beacon v2.2.0
    description: >-
      A Dataset is a collection of related sets of information, e.g. genomic
      variations together with associated procedural and biological metadata. In a
      Beacon context, a datasets may consist of information generated in a specific
      study or project, or represent the main content of the Beacon resource.
    defaultSchema:
      id: dataset
      name: Default schema for datasets
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/dataset
      schemaVersion: v2.2.0
    aCollectionOf:
      - id: genomicVariant
        name: Genomic Variants
      - id: biosample
        name: Biosamples
      - id: individual
        name: Individuals
      - id: analysis
        name: Genomic Analyses
    additionalSupportedSchemas: []
    # `bycon` config
    request_entity_path_id: datasets
    response_entity_id: dataset
    collection: Null
    response_schema: beaconCollectionsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: dataset
      schema: https://progenetix.org/services/schemas/dataset/
    is_beacon_entity: true
    path_id_value_bycon_parameter: dataset_ids
    tests:
      - description: default test mode
        test_values:
          testMode: true

  cohort:
    id: cohort
    name: Cohort
    ontologyTermForThisType:
      id: NCIT:C61512
      label: Cohort
    partOfSpecification: Beacon v2.2.0
    description: >-
      A group of individuals, identified by a common characteristic. [
      NCI ]
    defaultSchema:
      id: cohort
      name: Default schema for cohorts
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/cohort
      schemaVersion: v2.2.0
    aCollectionOf:
      - id: individual
        name: Individuals
    additionalSupportedSchemas: []
    # `bycon` config
    request_entity_path_id: cohorts
    response_entity_id: cohort
    collection: collations
    response_schema: beaconCollectionsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: cohort
      schema: https://progenetix.org/services/schemas/cohort/
    is_beacon_entity: true
    path_id_value_bycon_parameter: filters
    tests:
      - description: default test mode
        test_values:
          testMode: true

  genomicVariant:
    id: genomicVariant
    name: Genomic Variants
    ontologyTermForThisType:
      id: ENSGLOSSARY:0000092
      label: Variant
    partOfSpecification: Beacon v2.2.0
    description: >-
      Information about matching genomic variants from the corresponding dataset.
      The type of response used for the endpoint depends on the requested and granted
      `responseGranularity`.
    defaultSchema:
      id: genomicVariant
      name: Default schema for a genomic variation
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/genomicVariant
      schemaVersion: v2.2.0
    additionallySupportedSchemas: []
    # `bycon` config
    request_entity_path_id: g_variants
    request_entity_path_aliases:
      - genomicVariations
      - variants
    response_entity_id: genomicVariant
    collection: variants
    response_schema: beaconResultsetsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: genomicVariant
      schema: https://progenetix.org/services/schemas/genomicVariant/
    is_beacon_entity: true
    path_id_value_bycon_parameter: variant_ids
    tests:
      - description: default test mode
        test_values:
          testMode: true

################################################################################

  individual:
    id: individual
    name: Individual
    ontologyTermForThisType:
      id: NCIT:C25190
      label: Person
    partOfSpecification: Beacon v2.2.0
    description: >-
      Information about matching subjects (individuals) from the corresponding dataset.
      The type of response used for the endpoint depends on the requested and granted
      `responseGranularity`.
    defaultSchema:
      id: individual
      name: Default schema for an individual
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/individual
    additionallySupportedSchemas: []
    # `bycon` config
    request_entity_path_id: individuals
    response_entity_id: individual
    collection: individuals
    response_schema: beaconResultsetsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: individual
      schema: https://progenetix.org/services/schemas/individual/
    is_beacon_entity: true
    path_id_value_bycon_parameter: individual_ids
    examples:
      - ?filters=EFO:0030049&limit=5
    tests:
      - description: default test mode
        test_values:
          testMode: true

################################################################################

  biosample:
    id: biosample
    name: Biological Sample
    ontologyTermForThisType:
      id: NCIT:C70699
      label: Biospecimen
    partOfSpecification: Beacon v2.2.0
    description: >-
      Information about matching samples from the corresponding dataset.
      The type of response used for the endpoint depends on the requested and granted
      `responseGranularity`.
    defaultSchema:
      id: biosample
      name: Default schema for a biological sample
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/biosample
    additionallySupportedSchemas: []
    # `bycon` config
    request_entity_path_id: biosamples
    request_entity_path_aliases:
      - samples
    response_entity_id: biosample
    collection: biosamples  
    response_schema: beaconResultsetsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: biosample
      schema: https://progenetix.org/services/schemas/biosample/
    is_beacon_entity: true
    path_id_value_bycon_parameter: biosample_ids
    tests:
      - description: default test mode
        test_values:
          testMode: true

################################################################################

  run:
    id: run
    name: Experimental run
    ontologyTermForThisType:
      id: NCIT:C148088
      label: Sequencing run
    partOfSpecification: Beacon v2.2.0
    description: The valid and completed operation of a high-throughput sequencing
      instrument for a single sequencing process. [ NCI ]
    defaultSchema:
      id: run
      name: Default schema for a sequencing run
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/run
      schemaVersion: v2.2.0
    additionallySupportedSchemas: []
    # `bycon` config
    request_entity_path_id: runs
    response_entity_id: run
    collection: analyses  
    response_schema: beaconResultsetsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: run
      schema: https://progenetix.org/services/schemas/run/
    is_beacon_entity: true
    path_id_value_bycon_parameter: run_ids
    tests:
      - description: default test mode
        test_values:
          testMode: true

################################################################################

  analysis:
    id: analysis
    name: Bioinformatics analysis of a genomic experiment
    ontologyTermForThisType:
      id: edam:operation_2945
      label: Analysis
    partOfSpecification: Beacon v2.2.0
    description: >-
      Information about matching analyses from the corresponding dataset.
      The type of response used for the endpoint depends on the requested and granted
      `responseGranularity`.
    defaultSchema:
      id: analysis
      name: Default schema for a bioinformatics analysis
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/analysis
      schemaVersion: v2.2.0
    additionallySupportedSchemas: []
    # `bycon` config
    request_entity_path_id: analyses
    response_entity_id: analysis
    collection: analyses  
    response_schema: beaconResultsetsResponse
    bycon_response_class: BeaconDataResponse
    beacon_schema:
      entity_type: analysis
      schema: https://progenetix.org/services/schemas/analysis/
    is_beacon_entity: true
    path_id_value_bycon_parameter: analysis_ids
    tests:
      - description: default test mode
        test_values:
          testMode: true

################################################################################

  phenopacket:
    id: phenopacket
    name: Phenopacket
    ontologyTermForThisType:
      id: NCIT:C25190
      label: Person
    partOfSpecification: BeaconPlus
    description: >-
      Information about matching subjects (individuals) from the corresponding dataset,
      converted to Phenopackets format by aggregating the relevant information from
      the matched `individual`, `biosample`s, `analysis`(/es) and `genomicVariation`s.
    defaultSchema:
      id: phenopacket
      name: Default schema for an phenopacket
      referenceToSchemaDefinition: http://progenetix.org/services/schemas/phenopacket
    additionallySupportedSchemas: []
    # `bycon` config

