---
parameters:
  datasetIds:
    isHidden: false
    infoText: |
      Select one or more datasets to have their respective disease or other
      grouping derived CNV profiles (histograms) displayed.`
  assemblyId:
    isHidden: true
  geneId:
    isHidden: true
  aminoacidChange:
    isHidden: true
  genomicAlleleShortForm:
    isHidden: true
  referenceName:
    isHidden: true
  mateName:
    isHidden: true
  variantType:
    isHidden: true
  start:
    isHidden: true
  end:
    isHidden: true
  mateStart:
    isHidden: true
  mateEnd:
    isHidden: true
  cytoBands:
    isHidden: true
  variantQueryDigests:
    isHidden: true
  variantMinLength:
    isHidden: true
  variantMaxLength:
    isHidden: true
  referenceBases:
    isHidden: true
  alternateBases:
    isHidden: true
  cohorts:
    isHidden: true
  analysisOperation:
    isHidden: true
  bioontology:
    infoLink: "https://info.progenetix.org/doc/filters-documentation.html"
    infoText: |
      Select one or more datasets to have their respective disease or other
      grouping derived CNV profiles (histograms) displayed.
    isHidden: false
  referenceid:
    isHidden: true
  clinicalClasses:
    isHidden: true
  materialtype:
    isHidden: true
  sex:
    isHidden: true
  allTermsFilters:
    isHidden: true
  accessid:
    isHidden: true
  filterLogic:
    isHidden: true
  includeDescendantTerms:
    isHidden: true
  geoCity:
    isHidden: true
  geodistanceKm:
    isHidden: true
    defaultValue: null
  skip:
    isHidden: true
  limit:
    isHidden: true
  includeResultsetResponses:
    isHidden: true
